version: '3.4'
services:
  db:
    image: ankane/pgvector
    ports:
      - 5430:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mav3cm58ra3AVMI3W0IMV
      - POSTGRES_USER=bjoern
      - POSTGRES_DB=talk-to-docs

volumes:
  db:
